# Generated by Django 2.2.6 on 2020-01-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pen', 'Pending'), ('pub', 'Published'), ('rem', 'Removed')], default='pen', max_length=3),
        ),
    ]
