# Generated by Django 2.2.6 on 2020-01-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_welcome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name': 'welcome text', 'verbose_name_plural': 'welcome texts'},
        ),
        migrations.AddField(
            model_name='welcome',
            name='title',
            field=models.CharField(default='welcome_title', max_length=50),
        ),
    ]
